INSERT INTO `#prefix#_level_privlages` (`id`, `acc_point`, `descr`) VALUES
(1, 'm_see_admin_cp', NULL),
(2, 'u_upload', NULL),
(3, 'u_download', NULL),
(4, 'u_delete_own_torrents', NULL),
(5, 'm_delete_others_torrents', NULL),
(6, 'm_banusers', NULL),
(7, 'm_bann_torrents', NULL),
(8, 'm_bann_trackers', NULL),
(9, 'm_bann_shouts', NULL),
(10, 'a_see_ip', NULL),
(11, 'u_edit_own_comments', NULL),
(12, 'm_edit_comments', NULL),
(13, 'm_edit_user', NULL),
(14, 'm_mass_upload', NULL),
(15, 'u_view_nfo', NULL),
(16, 'u_requests', NULL),
(17, 'm_requests', 'Group can edit and delete Requests'),
(18, 'u_offers', NULL),
(19, 'm_offers', 'Group can edit and delete Offers'),
(20, 'u_top_torrentlist', NULL),
(21, 'u_can_comment', NULL),
(22, 'u_can_shout', NULL),
(23, 'u_can_change_theme', NULL),
(24, 'u_can_change_language', NULL),
(25, 'u_can_view_profiles', NULL),
(26, 'u_can_view_others_email', NULL),
(27, 'u_see_member_list', NULL),
(28, 'u_can_view_utube', NULL),
(29, 'u_can_add_uttube', NULL),
(30, 'u_hit_run', NULL),
(31, 'u_hnr_demote', NULL),
(32, 'u_arcade', NULL),
(33, 'u_can_use_bitbucket', NULL),
(34, 'u_black_jack', NULL),
(35, 'u_casino', NULL),
(36, 'm_can_edit_others_torrents', NULL),
(37, 'm_manage_faqs', NULL),
(38, 'm_edit_polls', NULL),
(39, 'm_modforum', NULL),
(40, 'm_del_users', NULL),
(41, 'u_edit_own_torrents', NULL),
(42, 'm_edit_others_shouts', NULL),
(43, 'u_masspm', NULL),
(44, 'u_masspm_group', NULL),
(45, 'u_pm_delete', NULL),
(46, 'u_pm_forward', NULL),
(47, 'u_pm_edit', NULL),
(48, 'u_pm_smilies', NULL),
(49, 'u_pm_bbcode', NULL),
(50, 'u_sig', NULL),
(51, 'u_savedrafts', NULL),
(52, 'u_pm_img', NULL),
(53, 'u_pm_flash', NULL),
(54, 'u_ignoreflood', NULL),
(55, 'u_sendpm', NULL),
(56, 'u_pm_attach', NULL),
(57, 'a_group', NULL),
(58, 'a_groupadd', NULL),
(59, 'a_groupdel', NULL),
(60, 'u_pm_download', NULL),
(61, 'u_sendim', NULL),
(62, 'group_receive_pm', NULL),
(63, 'a_clearlogs', NULL),
(64, 'a_forumadd', NULL),
(65, 'a_forumdel', NULL),
(66, 'a_fauth', NULL),
(67, 'a_authusers', NULL),
(68, 'a_authgroups', NULL),
(69, 'a_mauth', NULL),
(70, 'a_forum', NULL),
(71, 'f_list', NULL),
(72, 'f_post', NULL),
(73, 'm_approve', NULL),
(74, 'f_noapprove', NULL),
(75, 'a_warn_sys', NULL),
(76, 'a_prune', NULL),
(77, 'a_aauth', NULL),
(78, 'a_uauth', NULL),
(79, 'a_edit_level', NULL),
(80, 'a_override_user_pm_block', NULL),
(81, 'a_override_email_block', NULL),
(83, 'a_can_add_perm', 'Group can add new permissions to the site'),
(84, 'u_add_poster', 'Group can Add a poster in torrent details'),
(85, 'u_add_screen_shots', 'Group can add screen shots in torrent details'),
(86, 'u_add_nfo', 'Group can add a .nfo file to torrents details'),
(87, 'u_add_smiles_to_details', 'Group can add smile''s to Torrent Details'),
(88, 'u_add_bbcode_details', 'Group can Use bbcodes in Torrent Details'),
(89, 'u_add_quote_details', 'Group can use BBcode quot in Torrent Details'),
(90, 'u_add_imgbbcode_details', 'Group can use the BBcode tag img in Torrent Details'),
(91, 'u_links_in_details', 'Group can add link in Torrent Details'),
(92, 'u_flash_in_details', 'Group can use Flash code in Torrent Details'),
(93, 'u_upload_notify', 'Group can use Notify function in upload'),
(94, 'u_hide_torrent_owner', 'Group can hide Torrent owner while uploading'),
(95, 'u_apply_ratiobuild', 'Group can apply Ratio Build to torrent upload'),
(96, 'u_add_password_torrent', 'Group can add a Password to a torrent'),
(97, 'u_advance_upload_setting', 'Group can use Advanced features in upload\n''add private''\n''add dht'''),
(98, 'u_add_sticky_upload', 'Group can make new uploads Sticky'),
(99, 'u_shout_upload', 'Group can shout new Torrent uploads'),
(100, 'u_torrent_attach', 'Group can use Attachment feature for torrents'),
(101, 'u_can_add_magnet_links', 'Groups are allowed to upload/add Magnet and eD2k links'),
(102, 'm_view_whois', 'Group is able to view the Whois IP check'),
(103, 'm_casin_users', 'Group can Moderate Casino players.'),
(104, 'u_games', 'Group can play games'),
(105, 'm_mod_helpdesk', 'Group can Moderate the help desk witch includes Closing/Deleting Tickets.'),
(106, 'u_update_peers', 'Group can update Torrent peers.'),
(107, 'u_delete_comments', 'Group can delete there own comments'),
(108, 'm_delete_comments', 'Group Can delete others Comments'),
(109, 'a_mod', 'Gives Access to moderater functions in the admin pannel.'),
(110, 'a_admin', 'Gives group access to Admin sections of the Admin Pannel'),
(111, 'm_over_ride_password', 'Group Can See and down load PassWord protected Torrents.'),
(112, 'm_see_hidden_uploader', 'Group can see uploaders That have selected to Hid there upload'),
(113, 'u_can_view_snatchlist', 'Group Can View the Snatch List of a torrent Or User'),
(114, 'u_requist_reseed', 'Group can Requist Reseed on local Torrents'),
(115, 'm_down_load_private_torrents', 'Group can By pass Private setting on Torrents'),
(116, 'u_attach', 'Group Can Use forum Attachment'),
(117, 'u_search', 'Group Can use the Search feature in the Forum'),
(118, 'u_f_download', 'Group Can download forum Attachments'),
(119, 'm_warn', 'Group Can Warn Users');